# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactDemo
  pod 'React', :path => './node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
  ]
  target 'ReactDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
